name: Robot Framework Suite
on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      the-internet:
        image: gprestes/the-internet:v2.6.5
        ports:
          - 7080:5000

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # Cache pip packages matching requirements.txt

      - name: Run Environment Setup
        run: |
          python task.py setup

      - name: Run Robot Framework Tests
        run: |
          source venv/bin/activate
          python task.py test --headless

      - name: Upload Test Report Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-results
          path: results/
          retention-days: 30
